# Generated by Django 4.2.10 on 2025-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
