# Generated by Django 4.2.10 on 2025-07-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
