# Generated by Django 4.2.10 on 2025-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('none', 'No Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan')], default='none', max_length=10),
        ),
    ]
