# Generated by Django 4.2.10 on 2025-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
